set export := true
set ignore-comments := true
set positional-arguments := true
set shell := ["/usr/bin/env", "bash", "-euo", "pipefail", "-c"]

just := quote(just_executable()) + " --justfile=" + quote(justfile())

_default:
    @command {{ just }} --list
