# Scheme: Gruvbox Material Dark
# Author: Sainnhe Park (https://github.com/sainnhe)

[colors.primary]
background = "#1b1b1b"
foreground = "#d4be98"

[colors.cursor]
text = "#1b1b1b"
cursor = "#d4be98"

[colors.vi_mode_cursor]
text = "#1b1b1b"
cursor = "#d4be98"

[colors.selection]
text = "#e6d5ae"
background = "#282828"

[colors.normal]
black = '#3c3836'
red = '#ea6962'
green = '#a9b665'
yellow = '#d8a657'
blue = '#7daea3'
magenta = '#d3869b'
cyan = '#89b482'
white = '#ddc7a1'

[colors.bright]
black = '#665c54'
red = '#ed7e78'
green = '#b3be76'
yellow = '#ddb16c'
blue = '#8db8ae'
magenta = '#da99aa'
cyan = '#98be92'
white = '#e6d5ae'
