_just := quote(just_executable()) + ' --justfile=' + quote(justfile())
_setup_bash := 'set -euo pipefail'

set ignore-comments := true
set positional-arguments := true
set shell := ["/usr/bin/env", "bash", "-euo", "pipefail", "-c"]

_default:
    @{{_just}} --list
