#!/bin/sh
SHELL=/bin/sh
tmux list-sessions -F \
	'#{?session_last_attached,#{session_last_attached},0} #{session_id} #{session_name}' |
	# Sort by access time, then session name.
	sort -k1,1nr -k3 |
	# Remove columns that should not be displayed.
	cut -d' ' -f2- |
	# Return the id of selected session.
	fzf --accept-nth=1 --print-query --with-nth=2.. --preview="$HOME/.tmux/fzf_session_preview {1}" "$@" |
	{
		IFS= read -r query
		IFS= read -r selected
		if [ -n "$selected" ]; then # has a match, jump to target session
			tmux switch-client -t "$selected"
		elif [ -n "$query" ]; then # has no match, create the session and jump
			tmux new-session -ds "$query" \; switch-client -t "=$query"
		fi
	}
