edition = "2021"
unstable_features = true
# Useful unstable options
comment_width = 100
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_generated_files = false
format_strings = true
group_imports = "One"
imports_granularity = "Module"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_imports = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
