sourceDir: /home/yourname/dotfiles

# personal info
user: yourname
name: Your Name
email: yourname@example.com
home: /home/yourname
signingkey: xxxxxxxx

# customization
aria:
  port: 6800
  token: xxxxxxxx
atuin:
  address: https://api.atuin.sh
  token: xxxxxxxx
wakatime:
  address: https://api.wakatime.com/api/v1
  token: xxxxxxxx

# proxy services
proxy:
  enabled: true
  backend: xray
  httpPort: 1080
  socksPort: 1079
tor:
  enabled: false
  port: 1089
geodat:
  enabled: false
  ip: https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
  domain: https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
