sourceDir: /home/yourname/dotfiles
platform: linux # "linux", "termux"

# Personal info
user: yourname
name: Your Name
email: yourname@example.com
home: /home/yourname
hostname: Your Machine

# Appearance
font:
  monospace: 0xProto
  sansSerif: Noto Sans CJK SC
  serif: Noto Serif CJK SC

colors:
  scheme: Gruvbox Carbon Dark
  author: Sainnhe Park (https://github.com/sainnhe), Loi Chyan (https://github.com/loichyan)

  # Normal colors
  base00: "#0e0e0e"
  base01: "#1f1f1f"
  base02: "#35312f"
  base03: "#4b4440"
  base04: "#645a52"
  base05: "#ccb690"
  base06: "#d7c19c"
  base07: "#e3d2ab"
  base08: "#ea6962"
  base09: "#e78a4e"
  base0A: "#d8a657"
  base0B: "#a9b665"
  base0C: "#89b482"
  base0D: "#7daea3"
  base0E: "#d3869b"
  base0F: "#a89984"

  # Bright colors with lightness +5%
  bright:
    base00: "#101010"
    base01: "#222222"
    base02: "#393533"
    base03: "#504945"
    base04: "#6b6159"
    base05: "#d9c39c"
    base06: "#e4cea9"
    base07: "#f1e0b9"
    base08: "#f6746c"
    base09: "#f3955a"
    base0A: "#e5b263"
    base0B: "#b5c271"
    base0C: "#94c08d"
    base0D: "#88b9ae"
    base0E: "#df91a6"
    base0F: "#b3a48e"

# Programs
atuin:
  address: https://api.atuin.sh
  token: xxxxxxxx
wakatime:
  address: https://api.wakatime.com/api/v1
  token: xxxxxxxx
terminal: foot # "alacritty", "foot", "kitty", "wezterm", ...

# Services
aria:
  enabled: true
  port: 6800
  token: xxxxxxxx
gpg:
  enabled: true
  signingkey: xxxxxxxx
proxy:
  enabled: true
  backend: xray # "sing-box", "xray"
  httpPort: 1080
  socksPort: 1079
geodat:
  enabled: true
  ip: https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
  domain: https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
tor:
  enabled: true
  port: 1089
