sourceDir: /home/yourname/dotfiles
platform: linux # "linux", "termux"

# Personal info
user: yourname
name: Your Name
email: yourname@example.com
home: /home/yourname
hostname: Your Machine

# Appearance
font:
  monospace: 0xProto
  sansSerif: Noto Sans CJK SC
  serif: Noto Serif CJK SC

colors:
  scheme: Gruvbox Material Dark
  author: Sainnhe Park (https://github.com/sainnhe)

  base00: "#1b1b1b"
  base01: "#282828"
  base02: "#3c3836"
  base03: "#504945"
  base04: "#665c54"

  base05: "#d4be98"
  base06: "#ddc7a1"
  base07: "#e6d5ae"

  base08: "#ea6962"
  base09: "#e78a4e"
  base0A: "#d8a657"
  base0B: "#a9b665"
  base0C: "#89b482"
  base0D: "#7daea3"
  base0E: "#d3869b"
  base0F: "#a89984"

  # Bright colors with lightness +5%
  bright:
    base00: "#1e1e1e"
    base01: "#2b2b2b"
    base02: "#403c3a"
    base03: "#564f4b"
    base04: "#6d635b"
    base05: "#e1cba5"
    base06: "#ebd5ae"
    base07: "#f5e3bc"
    base08: "#f6746c"
    base09: "#f3955a"
    base0A: "#e5b263"
    base0B: "#b5c271"
    base0C: "#94c08d"
    base0D: "#88b9ae"
    base0E: "#df91a6"
    base0F: "#b3a48e"

# Programs
aria:
  port: 6800
  token: xxxxxxxx
atuin:
  address: https://api.atuin.sh
  token: xxxxxxxx
wakatime:
  address: https://api.wakatime.com/api/v1
  token: xxxxxxxx
terminal: alacritty # "alacritty", "kitty", "wezterm", ...

# Services
gpg:
  enabled: true
  signingkey: xxxxxxxx
proxy:
  enabled: true
  backend: xray # "sing-box", "xray"
  httpPort: 1080
  socksPort: 1079
geodat:
  enabled: true
  ip: https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
  domain: https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
tor:
  enabled: true
  port: 1089
