# Your profile
user: yourname
name: Your Name
email: yourname@example.com
home: /home/yourname
sourceDir: /home/yourname/dotfiles
atuinSyncAddress: https://api.atuin.sh
ariaPort: 6800
ariaToken: xxxxxxxx
signingkey: xxxxxxxx
wakamimeApiKey: xxxxxxxx
# Proxy ports
proxy:
  enabled: true
  backend: xray
  httpPort: 1080
  socksPort: 1079
tor:
  enabled: false
  port: 1089
geodat:
  enabled: false
  ip: https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
  domain: https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
