# Your profile
user: yourname
name: Your Name
email: yourname@example.com
home: /home/yourname
sourceDir: /home/yourname/dotfiles
atuinSyncAddress: https://api.atuin.sh
ariaPort: 6800
ariaToken: xxxxxxxx
signingkey: xxxxxxxx
wakamimeApiKey: xxxxxxxx
# Proxy ports
proxy:
  enabled: true
  port: 1080
  tor_port: 1089
