sourceDir: /home/yourname/dotfiles

# Personal info
user: yourname
name: Your Name
email: yourname@example.com
home: /home/yourname
hostname: Your_Machine

# Customization
aria:
  port: 6800
  token: xxxxxxxx
atuin:
  address: https://api.atuin.sh
  token: xxxxxxxx
gpg:
  enabled: true
  signingkey: xxxxxxxx
wakatime:
  address: https://api.wakatime.com/api/v1
  token: xxxxxxxx
terminal: kitty # "alacritty", "kitty", "wezterm"

font:
  monospace: Rec Mono Duotone
  sansSerif: Noto Sans CJK SC
  serif: Noto Serif CJK SC

# Proxy services
proxy:
  enabled: true
  backend: xray # "sing-box", "xray"
  httpPort: 1080
  socksPort: 1079
tor:
  enabled: true
  port: 1089
geodat:
  enabled: true
  ip: https://github.com/v2fly/geoip/releases/latest/download/geoip.dat
  domain: https://github.com/v2fly/domain-list-community/releases/latest/download/dlc.dat
