#!/usr/bin/env bash

# source global definitions
if [[ -f /etc/bashrc ]]; then
	. /etc/bashrc
fi

# user specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi
unset rc
